### ISSUE TITLE
Option to rearrange columns in Project View

### ISSUE THREAD

**Issue by akitaonrails** [Codeminer42/cm42-central#100]
Just like Pivotal Tracker the main columns are ordered this way:

Done -> Current Sprint -> Backlog -> Chilly Bin -> Search Results (optional)

it means that new stories start at the right-side of the screen and "flow" to the left.

All of the other "kanban-like" tools have a different order:

Backlog -> In Progress -> Done

Generic post-it systems all start accumulating cards in the left-side and moving them to the right-side.

So we could have a button, checkbox, user preference where we can invert the order of our columns to be:

Chilly Bin -> Backlog -> Current Sprint -> Done

I still think the Tracker way is correct, but most people might find it confusing if coming from Trello, or Github/Gitlab boards, and others.

**Comment by andrerpbts** [comment]
Closed by https://github.com/Codeminer42/cm42-central/pull/118
