### ISSUE TITLE
First Time Interface Tour

### ISSUE THREAD

**Issue by akitaonrails** [Codeminer42/cm42-central#102]
We must add possibly 2 fields in the users table:

- tour, boolean, default: true. When tour is false, no bubbles will show up
- tour_steps: text, a string with probably a JSON state of all the bubbles. Whenever a new bubble is shown to the user, we must update it so it doesn't show anymore. That's because the tutorial is not linear. For example, the bubbles explaining a New Story will only show up when the user first clicks on the "New Story" button.

The user must be able to reset the tour from his User Profile edit page or totally disable the tour in the first bubble (the "check here if you already know how to use this product"). 

One possible library to use is [Shepherd](https://github.com/HubSpot/shepherd) (cc @talyssonoc)

### Choose Team

The first bubble must show up at the Team selection right after he signs up. There is no Team in the first time so the first bubble must guide to "New Team" button saying:

"You must create a new Team to start, you will become the administrator of the Team. Teams can have many members and many projects and you can participate in multiple teams at the same time"

### Dashboard

When a new Team is created and selected, there will be no activities and no projects, so the next bubble must point to the "New Project" button saying:

"You can create as many projects as you want clicking this button"

The next bubble should also highlight the Activities panel saying:

"Every time you change something in the Project or its Story they will be audited and the details of the changes will be visible to every team member from this Activity timeline box. Pro tip: you shouldn't change a Story after the team started working on it, you must add a new Story."

### Project View

1) When a user creates a new project, the board will be empty. The first bubble must point to the "Add Story" button saying:

"Click this button to create new Stories. A Story can be the description of a new feature or a bug report, for example. New stories will be created first at the Chilly Bin box."

2) Then a new bubble must point to the Chilly Bin column title saying:

"All new stories are stores in this Chilly Bin. You should describe your stories expecting that the description and attachments will suffice for the story to be implemented. Project members should estimate those stories.".

3) The next bubble must point to the Backlog column saying:

"The backlog MUST have all stories by order of PRIORITY. Most valuable and ready-to-start stories at the top and optional or uncertain stories at the very bottom".

4) The next bubble must point to the In Progress column saying:

"This is where stories that must be worked on right now will reside. Central will automatically pick up the top stories from the Backlog to fit the team's current Velocity".

5) The next bubble must point to the Velocity indicator at the top bar saying:

"All stories are estimated by "points". The average of points delivered by a team during an Iteration is the Velocity. The estimated end date of a Project is the total amount of points in the Backlog divided by the Velocity. Here you can simulate adding a new member by slightly increasing the estimated Velocity to see the effects on the future Iteration dates".

6) The next bubble must point to the Done column saying:

"After a story is delivered and approved, it is sorted out at the bottom of this column. A delivered story can't be modified and this column is here to show you everything that has already been finished and approved".

7) The next bubble must point to the Members column saying:

"If you want to add or remove people from the Project team, click here"

This is the basics, we can add and tweak more later, but I think that if we have at least this much, it should help new comers.

All text must be in the localized files so we can translate them.

And if we add new bubble later, because they will not be in the "tour_steps" field, only those will show for all users when we add them. This is the mechanism to allow for new bubbles and so users don't see repeated bubbles in the future unless they ask to in the profile edit page.

**Comment by FidelisClayton** [comment]
@akitaonrails  I'll do this!

**Comment by PedroFelipe** [comment]
fixed on #106
