### ISSUE TITLE
Points displayed as numbers instead of stack

### ISSUE THREAD

**Issue by AltarBeastiful** [Codeminer42/cm42-central#105]
After updating our instance to the latest master branch, we noticed the points of each story are displayed as numbers. Before it was displayed as a stack like on Pivotal.

![New display behaviour](https://cloud.githubusercontent.com/assets/3317699/22286958/41d7e4fe-e2f1-11e6-98a2-f4e3c309809f.PNG)

We would like to switch back to the previous way of displaying the points, as we find it easier to read.

Was this modification in the latest commits, or there is a setting controlling this?

**Comment by PedroFelipe** [comment]
https://github.com/Codeminer42/cm42-central/commit/f29cb150ec41ede4d00a573daf90f839dc1a96f5#diff-e00c9d09a63bf3d26ffb5966f3205679L34
