### ISSUE TITLE
Team logo upload is not working

### ISSUE THREAD

**Issue by marcosjr182** [Codeminer42/cm42-central#116]
Team logo image upload is not working.

![edit_team](https://cloud.githubusercontent.com/assets/5242693/22830365/00f35b62-ef85-11e6-9ce4-d268ed3a8507.png)

**Comment by alceumedeiros** [comment]
#121

**Comment by alceumedeiros** [comment]
Fix team logo image upload #121

**Comment by marclerodrigues** [comment]
Since it was fixed by #121 I'm closing this issue.
