### ISSUE TITLE
[Suggestion] Stop being a fork

### ISSUE THREAD

**Issue by acrogenesis** [Codeminer42/cm42-central#149]
It would be nice a "standalone" repo was used instead of a fork mainly because the search function doesn't work on forks.

**Comment by akitaonrails** [comment]
I agree. Anyone know how to unlink the repo from being a fork without having to recreate from scratch (and lose the issues)?

**Comment by adbatista** [comment]
need to send an email to github team

**Comment by acrogenesis** [comment]
To detach the fork and turn it into a standalone repository on GitHub, contact [GitHub Support](https://github.com/contact). If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network.

Found it on https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

**Comment by PedroFelipe** [comment]
Resolved.
