### ISSUE TITLE
Server will not run after successful installation

### ISSUE THREAD

**Issue by graeme-defty** [Codeminer42/cm42-central#151]
After what appeared to be a successful installation (non-docker) I got the following when I tried to start the server:

    15:55:45 web.1     | started with pid 1988
    15:55:45 worker.1  | started with pid 1989
    15:55:45 webpack.1 | started with pid 1991
     70% 1/1 build modules http://0.0.0.0:3808/
    15:55:54 webpack.1 | webpack result is served from //localhost:3808/webpack/
    15:55:54 webpack.1 | content is served from /home/graeme/cm42-central
    15:55:57 worker.1  | exited with code 1
    15:55:57 system    | sending SIGTERM to all processes
    15:55:57 webpack.1 | terminated by SIGTERM
    15:55:58 web.1     | exited with code 0

Nothing in the log directory looked amiss.

Any suggestions where I could look to try and diagnose the problem?

Thanks

**Comment by acrogenesis** [comment]
I had a similar problem what was missing was redis.

**Comment by eddiecode** [comment]
Hey @graeme-defty, try to run `redis-server` before.

**Comment by fladson** [comment]
I think we could add this step on README

**Comment by graeme-defty** [comment]
Guys, thanks for the help.

This was exactly what was required.  :-)
