### ISSUE TITLE
CSV import fails

### ISSUE THREAD

**Issue by stweb** [Codeminer42/cm42-central#181]
When I export the test project, create a new project and try to import. The AJAX API call fails with 401 {"error":{"message":"Invalid api_key username"}}

The UI shows the upload %, the resets without error message.

Actually all attachments fail - I assume it's a config issue with Attachinary? I'm running the app on MacOS Sierra. Is it possible to run without a Cloudinary account?

Also, I noticed the REST API - would be great if it supported creating stories.

**Comment by alceumedeiros** [comment]
I don't think it's possible to run without a Cloudinary account. I just tried and got the same error. 
But with a Cloudinary account it works fine! You just need to create an account and set `CLOUDINARY_URL` correctly.
