### ISSUE TITLE
Improve release stories

### ISSUE THREAD

**Issue by andrerpbts** [Codeminer42/cm42-central#184]
Until now, releases stories was being handled as a normal story, with a simple purpose to separate stories in groups. From now, we need to design it in a way it effectively informs the users about the release expectation.

First off, we need to add a date field to it, called release_date, to store the expected date the release should be launched, with a date picker. Also, release stories just need some fields which normal stories have: Title, Story Type, Release Date and Description.

After that, the release story should dynamically check its iteration date when it was rendered (based in the velocity), and compare with its release date specified. If the iteration start date is greater than release date, then the release should change something in its aspect (like color, background color, icon, w/e) to make visible that it will break the release date expectation.

A more detailed description of how a release story must behave can be found at [Pivotal Tracker documentation](https://www.pivotaltracker.com/help/articles/organizing_releases/). Ours must work the exact same way.

1. [x] Add the release date field, and persist it. Remove uneccessary fields from release story.
2. [x] Highlight the release story if the release date is compromised.

**Comment by IgorVieira** [comment]
Please, 
What do you mean by `iteration date`?
