### ISSUE TITLE
ActionView::Template::Error (Must supply cloud_name):

### ISSUE THREAD

**Issue by kanekoh** [Codeminer42/cm42-central#185]
Tried to build cm42-central from scratch with docker-compose on Windows 10.
 
After executing docker-compose up, creating a new project failed because of the following error.

```
web_1       | ActionView::Template::Error (Must supply cloud_name):
web_1       |     1: <%= javascript_tag "var ATTACHINARY_OPTIONS = #{attachinary_file_field_options(Story.new, :documents, cloudinary: { use_filename: true }).to_json}" %>
web_1       |     2: <%= raw File.read Rails.root.join('app/views/projects/_attachinary_template.html') %>
web_1       |     3:
web_1       |     4: <%= render partial: 'sidebar',
```

What am I missing?

The below is my environment.
- Docker for Windows: docker-compose version 1.11.2, build f963d76f
- cm42-central: using latest master branch source code.

Thanks in advance.

**Comment by alceumedeiros** [comment]
I believe you forgot the `cp .env.sample .env` part.
`.env` sets `CLOUDINARY_URL` variable, which is what's missing in that case!

**Comment by kanekoh** [comment]
Thanks @alceumedeiros, It works. 
I just want to know if there is any settings to build cm42-central. 

I thought that the section of using docker in readme needs to add the following part.
```
$ cp .env.sample .env
$ cp config/database.yml.example config/database.yml
```

**Comment by alceumedeiros** [comment]
You're absolutely right @kanekoh. It's not that you forgot to copy, it just isn't specified in the README file for the `docker` setup part!
