### ISSUE TITLE
Docker Compose - unexpected token at 'Invalid Host header'

### ISSUE THREAD

**Issue by maralik** [Codeminer42/cm42-central#199]
Hi!
I've download the repository and launched as it's written for docker:

> # Checkout the project
> $ git clone git://github.com/Codeminer42/cm42-central.git
> $ cd cm42-central
> 
> # copy and edit the configuration
> $ cp .env.sample .env
> $ cp config/database.yml.example config/database.yml
> 
> # Prepare container
> $ docker-compose build
> $ docker-compose run --rm web npm install
> $ docker-compose run --rm web bundle exec rake db:create
> $ docker-compose run --rm web bundle exec rake db:migrate
> $ docker-compose run --rm web bundle exec rake db:seed
> 
> # Up container
> $ docker-compose up
> 

I cannot start the app:

![error](https://user-images.githubusercontent.com/905799/27105223-13bb95b4-508f-11e7-8e07-6f4b274f3bb1.png)

The log from the starting up the app is in the attachment - after:
> $ git clone git://github.com/Codeminer42/cm42-central.git
> $ cd cm42-central
> 
> # copy and edit the configuration
> $ cp .env.sample .env
> $ cp config/database.yml.example config/database.yml

There is the log from terminal (running on Mac OS):
[docker-output.txt](https://github.com/Codeminer42/cm42-central/files/1072937/docker-output.txt)

Thank you in advance.

**Comment by fladson** [comment]
Hey @maralik thanks for letting us know about this and for the detailed report.
I saw at your log that `webpack` wasn't installed properly, have you tried to install it separately? 

`Error: Cannot find module 'webpack'`

**Comment by maralik** [comment]
Hey @fladson I've tried now, but didn't help - now is docker-compose-up without errors but still I'm getting the same error. The log in the attachment.

[log-webpack-install.txt](https://github.com/Codeminer42/cm42-central/files/1075115/log-webpack-install.txt)

**Comment by maralik** [comment]
Hello @fladson please, when you clone the repository and try to launch it as it is written in the documentation, do you get the same error as me? It would really help me to understand.

Thank you!

**Comment by fladson** [comment]
Yes @maralik I've tried a clean docker setup and got the same error as you, still trying to find out the cause.

**Comment by maralik** [comment]
Thank you!

**Comment by kanekoh** [comment]
I was wondering if you put ` --public webpack ` at weback.command in your docker-compose.yml file like following. it works fine for me. 

```
command: webpack-dev-server --hot --inline --progress --host 0.0.0.0 --public webpack --config config/webpack.config.js
```

**Comment by maralik** [comment]
This works, thank you!
