### ISSUE TITLE
Minor design corrections

### ISSUE THREAD

**Issue by marcosjr182** [Codeminer42/cm42-central#200]
:nail_care: There are a few different minor style bugs on the project appearance. Anyone is welcome to follow up, add new bugs or fix them.

- [x] Team's edit form has a button not matching it's input size.
  ![teams_edit](https://user-images.githubusercontent.com/5242693/27182747-ae014046-51b2-11e7-9c0a-420f896eeaa5.png)

- [x] Project members list on `projects/:team_slug/users` has missing margins on users' photo.
  ![projects_users](https://user-images.githubusercontent.com/5242693/27183005-88189414-51b3-11e7-81c5-a17d8030b47e.png)

- [x] Project Settings sidebar's divider has two lines instead of one
  ![project_settings_sidebar](https://user-images.githubusercontent.com/5242693/27182583-19ff7c00-51b2-11e7-9493-c0516333da0d.png) 

- [x] Tag Input group button is not matching the input size and it is not correctly following the panel paddings on `projects/form` 
  ![tag_button](https://user-images.githubusercontent.com/5242693/27182404-67254c4a-51b1-11e7-992a-624b4b205a1f.png)
  ![tag_projects_new](https://user-images.githubusercontent.com/5242693/27183465-085a184a-51b5-11e7-901d-117cd6841d4a.png)

**Comment by iagodahlem** [comment]
Hey @marcosjr182, which browser do you use? I was seeing the first and last item that you appointed (locally and in prod), and it's OK in my browser.

![image](https://user-images.githubusercontent.com/11875867/27400796-9f126134-5697-11e7-933b-dbe90f50bc86.png)

**Comment by marcosjr182** [comment]
I've taken those screenshots on a Google Chrome 😕 Since it looks fine on production, maybe it's being caused by some local issue.. =) I'll check it out and remove it from the issue.. o/ thanks!

**Comment by andrerpbts** [comment]
Adding this to backlog.
