### ISSUE TITLE
Is there a VM, docker image or vagrant image ?

### ISSUE THREAD

**Issue by richardhughes260** [Codeminer42/cm42-central#219]
Is there a VM, docker image or vagrant image ?

I am having trouble setting up the Ruby / Rails  environment, a VM would be amazingly helpful!

**Comment by igorrfc** [comment]
Hey @richardhughes260,

I think that the image used on the gitlab-ci config file should works for you. Take a look [here](https://hub.docker.com/r/codeminer42/ci-ruby/) and let me know if the issues were solved.

Hope that helps.

**Comment by richardhughes260** [comment]
THANKS! Will check it out!
