### ISSUE TITLE
Can't add description in release story

### ISSUE THREAD

**Issue by Laffarli** [Codeminer42/cm42-central#238]
In v1.5 version it was still possible to add description in release story, which was very usefull.
Now it seems description has been removed.
We are stuck on this version because we need to be able to add descriptions on the releases.
I hope this is a bug and not a choice.

**Comment by andrerpbts** [comment]
This question was rethinked and we decided to bring description field back. This issue is in our backlog now.

**Comment by Laffarli** [comment]
Good news! :)
We look forward to the delivery of this update.

**Comment by andrerpbts** [comment]
v1.11.0 was launched with this bug solved. 🎉
