### ISSUE TITLE
[Features] Improve search box/search results

### ISSUE THREAD

**Issue by SUTJael** [Codeminer42/cm42-central#256]
Hi,

Would be great to be able to:

- ~handle some search operators (like name:"", owner:"", etc.) to be able to search for specific stories. (additionally, adding a left menu "Mine" filter which would do an owner:"" search)~ ✅

- ~handle mouse drag&drop for stories displayed in search results. When you have many stories in chilly bin and you're searching for one of them, there's no possibility to drag the result to a specific backlog sprint. The only way is to use the "browser" find box to highlight the story and then drag it.
Would it be possible to drag directly from the search box or maybe to have a new "highlight" button that will scroll/hightlight the "real" story?~ ✅

- ~add a duplicate button to create a story in chilly bin with exact same content~ ✅

Thanks for your great job.

**Comment by andrerpbts** [comment]
We are considering to bring it to the backlog.

Can you, please, post here a gif showing the second item issue happening?

Thanks

**Comment by SUTJael** [comment]
Thank you.

About the second item, I've created a demonstration project to show you:

![cm42_dragndrop](https://user-images.githubusercontent.com/5746257/30847639-8abdae22-a29c-11e7-9a19-d0a9c117d242.png)

On our side we have plenty of chilly bin stories (100 and more) so we really need to use the search box to identify one of them and bring it to the "search results panel". The purpose of my request is to be able to drag'n'drop the search result item to the backlog. Otherwise after "searching" you can just edit the story but you need to use the browser search box to highlight the "real" (i.e chilly bin) story and drag it to the backlog.
If too hard, my suggestion was to add a new button to automatically scroll and highlight the "real" story into panels (progress, backlog, chilly bin).

Thanks again

**Comment by andrerpbts** [comment]
Good,

I'm moving this to a separated issue, and this will be implemented first.

Thank you!
