### ISSUE TITLE
Velocity on projects index, in some cases, differs from the velocity on projects dashboard

### ISSUE THREAD

**Issue by Drowze** [Codeminer42/cm42-central#266]
As soon as #265 gets merged, it will highlight another issue (much smaller though):

(taken from PR #265):
>The frontend always use the last 3 iterations with one or more done stories to calculate the velocity. If, for an example, there are no stories on the past iteration and the one before it, it will still use the ones before them until there is 3 iterations with at least one accepted story each (or unless it realizes there are less than 3 iterations). This logic is on app/assets/javascripts/models/project.js.
>
>The backend, however, will only look for done iterations on the past month. If there is less than three iterations on the last month, it will not even look for the past stories. This logic is encapsulated on IterationService class on central-support gem, and evoked at ProjectPresenter#velocity.
>
>It should be noted too, the backend calculates the projects' velocities displayed on Project index, while the frontend calculates the velocity on Project dashboard.

I would like comments on which approach should we take to solve this.

---

Script to reproduce:
https://gist.github.com/Drowze/5f66d3e8f90f882730d0f2163e64ec61

The projects' index:
![image](https://user-images.githubusercontent.com/9031589/30935050-d627fce6-a3a5-11e7-93c5-0c4134bade59.png)

The project dashboard:
![image](https://user-images.githubusercontent.com/9031589/30935189-4c8521de-a3a6-11e7-9f34-4bc8a6188e0f.png)
![image](https://user-images.githubusercontent.com/9031589/30935214-5822e968-a3a6-11e7-9578-a6cff3ddb234.png)

**Comment by carloslopes** [comment]
Imagine a scenario where we have a project with 5 sprints with the following sum of points:
Sprint 1: 6 points
Sprint 2: 10 points
Sprint 3: 0 points
Sprint 4: 0 points
Sprint 5: 24 points

The right approach to calculate this team velocity is sum the **last 3 sprints** points and divide the result by 3 (following our example: `(0 + 0 + 24) / 3 => 8`)
