### ISSUE TITLE
Reverse Chilly Bin insertion order

### ISSUE THREAD

**Issue by AltarBeastiful** [Codeminer42/cm42-central#269]
In our workflow we tend to use the Chilly Bin for 2 things : 

* Stories that are being refined
* Stories that we might want to do someday, but are still unusure

With that comes a big stock of stories in the Chilly bin making it harder to actually see the stories still being actively refined. 

Could we add an option to invert the insertion order of the Chilly Bin so that newer, fresher stories gets added on top and can be moved in a lower position if they get actually *cold* ?

**Comment by andrerpbts** [comment]
Hi,

Based in your statements, I'm considering in add to the backlog a feature to really invert the order where stories are created in chilly bin, to newer stories first - older stories last. 

However, in this case, I prefer to make it the default flow instead put any config/option to change behaviors.

Adding a feature label to this issue by now.

**Comment by andrerpbts** [comment]
This feature was implemented and I'm closing this.

Now, by default, new chilly bin stories will be created in the top of that column.
