### ISSUE TITLE
[Features] Hide and collapse past iterations

### ISSUE THREAD

**Issue by Laffarli** [Codeminer42/cm42-central#285]
Hello,
We use cm42-central for few months now and we need to scroll a lot only to see what's happen on the last iteration. The "Done" column begins complicated to use.

It would be great if the "Done" column was managed exactly like "Pivotal Tracker":

- Collapse all past sprint except last one.
- Display only last 12 iterations.
- Be able to click to load all past iterations but collapsed.

A big thank you for your work.

**Comment by andrerpbts** [comment]
Adding it to backlog!

Thanks!
