### ISSUE TITLE
Refactor ColumnView into a React component

### ISSUE THREAD

**Issue by vitortalaia** [Codeminer42/cm42-central#286]
In order to be able to finish #183, we need to take the following steps:

- [ ] Convert `column.ejs` to a component keeping the jQuery parts inside `componentDidMount`
- [ ] Extract from Backbone view to an actual React component
- [ ] Split the `ColumnView` component into a container and a dumb component

**Comment by Lukyhenson** [comment]
@vitortalaia has someone working on this issue?

**Comment by vitortalaia** [comment]
@Lukyhenson Nope, feel free to take a look at it. I'd suggest you reach out @talyssonoc to see if this issue is still relevant.

**Comment by talyssonoc** [comment]
It's not gonna be necessary anymore since we're now working on v2.
