### ISSUE TITLE
Do not scroll down when creating a new story.

### ISSUE THREAD

**Issue by Laffarli** [Codeminer42/cm42-central#309]
First of all, I wanted to wish you a happy new year and to thank you again for the great work you do.

Since you reversed the order of the Chilly Bin (which is nice), when creating a new story, an automatic scroll down is still done in the Chilly Bin. We do not see the new story that is being created and so we have to scroll back to the top of the page again.

**Comment by andrerpbts** [comment]
Hello,

Added to backlog to fix it.
