### ISSUE TITLE
Importing stories in a new project after an export from an existing project doesn't work

### ISSUE THREAD

**Issue by Laffarli** [Codeminer42/cm42-central#317]
We were trying to move stories from a project to an other using import/export functionnality but it doesn't work.
The csv file seems to be malformatted.
Carriage returns that are in the description or comments are saved in the csv file as a carriage return, which breaks the CSV format.

**Comment by andrerpbts** [comment]
I tried to use this functionality and, apart from another issue that I'm fixing in  https://github.com/Codeminer42/cm42-central/pull/379, I could make this import successfully.
