### ISSUE TITLE
Copy notes content from story

### ISSUE THREAD

**Issue by cerdiogenes** [Codeminer42/cm42-central#353]
When you add a note to a story, you can't select the note text, it's behave like an image, although inspecting the element it's a \<p\>.

**Comment by andrerpbts** [comment]
@gutofoletto Can you, please, take a look into this when you have a chance?

**Comment by gutofoletto** [comment]
@andrerpbts sure!

**Comment by gutofoletto** [comment]
@andrerpbts I was looking into it now and It seems that when you try to select a note or a description the `drag n' drop` behaviour is triggered because the entire story element is `draggable`.

**Comment by gutofoletto** [comment]
if I change the `handle` to be only the title of the `story` everything becomes selectable again. Do you think this approach is okay?

**Comment by andrerpbts** [comment]
@gutofolleto not sure, maybe there’s something we can do to prevent dragging only for this component...
