### ISSUE TITLE
Add Spanish translation for velocity strategy 

### ISSUE THREAD

**Issue by kostadriano** [Codeminer42/cm42-central#426]
# First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who haven't contributed to an open source project before.

If you have contributed before, consider leaving this one for someone new. Thanks!
# The Problem

On project edit page one translate in Spanish is missing on Velocity strategy field.

![screenshot_20181210_175340](https://user-images.githubusercontent.com/15300776/49758056-1d872680-fca5-11e8-9b30-83002fa7133b.png)

# The Solution
In central we have 3 idioms available and each one is kept in a yaml file.
- Brasilian Portuguese: config/locales/pt-BR.yml
- English: config/locales/en.yml
- Spanish: config/locales/es.yml

It's necessary to write a spanish translate for velocity strategy in [this file](https://github.com/Codeminer42/cm42-central/blob/master/config/locales/es.yml), in two different lines.

AND REMEMBER: Indentation in YAML files it's really important.

In line [134](https://github.com/Codeminer42/cm42-central/blob/master/config/locales/es.yml#L134) we need to add this:

```diff
  n weeks:
    one: '1 semana'
    other: '%{count} semanas'
+
+ n velocity strategy:
+   one:    'Promedio de 1 interacción'
+   other:  'Promedio de %{count} interacciones'
+  
  keycuts:
    keyboard_shortcuts: Atajos de teclado
```

And this in line [171](https://github.com/Codeminer42/cm42-central/blob/master/config/locales/es.yml#L171), right below mail_reports

```diff
        archived:             'Archivado'
        mail_reports:         'Enviar informes por correo electrónico'
+       velocity_strategy:    'Estrategia de velocidad'
     story:
        title:                'Título'
```

# Steps to Fix
 - [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
 - [ ] Fork the repository and set it up locally following the main repo README instructions https://github.com/Codeminer42/cm42-central
 - [ ] Create a new branch with a unique name descriptive to the issue
 - [ ] Try to fix the issue following the steps above, but even before you're done, you can:
commit your changes to your branch and start a pull request. If you need you can always ask for help.
 - [ ] Reference this issue in the pull request body
 
[Here](https://github.com/firstcontributions/first-contributions) you can see in several languages a step by step how to contribute for the first time.

If you need some help you can comment below or send a message. 
Good luck with your first PR !!!   :top::ok_hand::bowtie:

**Comment by kostadriano** [comment]
Thanks! :smile:

**Comment by vitortalaia** [comment]
![image](https://user-images.githubusercontent.com/5838414/52281074-6e816700-2944-11e9-88e5-f50b3d223a01.png)
