### ISSUE TITLE
Change out of date link in README

### ISSUE THREAD

**Issue by kostadriano** [Codeminer42/cm42-central#428]
# First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who haven't contributed to an open source project before.

If you have contributed before, consider leaving this one for someone new. Thanks!

# The Problem
One link in the description of the [project](https://github.com/Codeminer42/cm42-central) is out of date, so when a user clicks, it will send him to a 404 page.

> ![image](https://user-images.githubusercontent.com/15300776/49620628-eebd3780-f9a8-11e8-8776-91e8e092f82f.png)

Results in:
> ![image](https://user-images.githubusercontent.com/15300776/49620643-01d00780-f9a9-11e8-8b83-1023df8f9631.png)

# The Solution
You need to edit [README.MD](https://github.com/Codeminer42/cm42-central/blob/master/README.md) file in lines (93 - 94) to remove the old link and put the new one.

```diff
- First up, your system will need the
- [prerequisites for running Ruby on Rails installed](http://rubyonrails.org/download)

+ First up, your system will need the
+ [prerequisites for running Ruby on Rails installed](https://guides.rubyonrails.org/getting_started.html)
```

# Steps to Fix
 - [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
 - [ ] Fork the repository and set it up locally following the main repo README instructions https://github.com/Codeminer42/cm42-central
 - [ ] Create a new branch with a unique name descriptive to the issue
 - [ ] Try to fix the issue following the steps above, but even before you're done, you can:
commit your changes to your branch and start a pull request. If you need you can always ask for help.
 - [ ] Reference this issue in the pull request body
 
[Here](https://github.com/firstcontributions/first-contributions) you can see in several languages a step by step how to contribute for the first time.

If you need some help you can comment below or send a message. 
Good luck with your first PR !!!   :top::ok_hand::bowtie:

**Comment by EmersonManabuAraki** [comment]
I got this issue to fix it
