### ISSUE TITLE
Docker image only responds to the local host, how do I change that?

### ISSUE THREAD

**Issue by richardhughes260** [Codeminer42/cm42-central#457]
I'm very excited about the docker image! It works great!

How do I Change the docker image so that it responds to all requests from the network, not just localhost?

**Comment by paulodiovani** [comment]
Can you give us a bit more info on what errors do you get?

BTW, it's worthy to remember that `docker-compose` is not to be used for production.

**Comment by richardhughes260** [comment]
In the docker-compose.yml file if you change all the server names that end in .localhost to your local domain & either make a DNS or host file entry for IP resolution, it will be accessible to other computers on the lan.

**Comment by paulodiovani** [comment]
I have never done that.
Can you provide an example of your `docker-compose.yml`?

**Comment by paulodiovani** [comment]
I still didn't get if you're trying to access the containers from inside the docker network (e.g. other services in the same docker-compose.yml) or from computers on the same network as the host.
