### ISSUE TITLE
Rollbar warning about no route for favicon.ico

### ISSUE THREAD

**Issue by talyssonoc** [Codeminer42/cm42-central#494]
Looks like there is somewhere in the code that tries to use the favicon in a wrong way and we get the following error in Rollbar:

`ActionController::RoutingError: No route matches [GET] "/assets/favicon.ico"`

Looks like it happens because of these lines: https://github.com/Codeminer42/cm42-central/blob/master/app/assets/javascripts/mixins/tab_notification.js#L7-L9

It would be good to solve this so we don't receive unnecessary warnings about it.

--

How to reproduce the problem:

Open two tabs within the same board, change something in one of the tabs, the second one should change the icon.

--

Proposed solution:

Add two data attributes to `body` tag:

```erb
   data-notification-icon-url="<%= asset_url('notification.icon') %>"
   data-favicon-icon-url="<%= asset_url('favicon.icon') %>"
```

And use it like this:

```js
      this.handleChangeTitle(notificationTitle, $('body').data('notificationIconUrl'));
    } else {
      this.handleChangeTitle(title, $('body').data('faviconIconUrl'));
```

**Comment by Diego-Thomaz** [comment]
I'll check this one

**Comment by Diego-Thomaz** [comment]
It's done. PR is opened!
