### ISSUE TITLE
Replace PhantomJS with Selenium Webdriver

### ISSUE THREAD

**Issue by talyssonoc** [Codeminer42/cm42-central#496]
We use [PhantomJS](http://phantomjs.org/) for our feature tests but it has some problems that should be considered:

- [Phantom has its development suspended](https://github.com/ariya/phantomjs/issues/15344)
- Is is too behind modern browsers so we end up adding a *lot* os polyfill for our tests to run on that
- It is slow

We began to replace Phantom with Selenium Webdriver in this PR #380 but we needed to stop it because we weren't getting anywhere since Selenium Webdriver simply doesn't have some operations Phantom does, we need to investigate it deeper.

**Comment by marclerodrigues** [comment]
This issue was closed on #498
