### ISSUE TITLE
Export CSV breaks when there are no stories in the project

### ISSUE THREAD

**Issue by talyssonoc** [Codeminer42/cm42-central#513]
### Problem

When a project has no stories it can't be exported. It's an unlikely scenario but not impossible.

### Steps to reproduce

1. Create a new project
2. When the page of the boards, click in the `Export` button without adding any story
3. Face an error page

### Probable solution

The error happens in these lines https://github.com/Codeminer42/cm42-central/blob/master/config/initializers/csv_renderer.rb#L27-L29 because `number_of_extra_columns[:notes]` is empty and can't be passed as value to the Array constructor.

It happens because [`Array#max`](https://github.com/Codeminer42/cm42-central/blob/master/config/initializers/csv_renderer.rb#L5-L7) returns `nil` when the array is empty.

**Comment by cmatiello** [comment]
I'll do this =)
