### ISSUE TITLE
Refactor "export to CSV" process

### ISSUE THREAD

**Issue by talyssonoc** [Codeminer42/cm42-central#517]
### What

Currently, the CSV generation is being directly in the [initializer](https://github.com/Codeminer42/cm42-central/blob/master/config/initializers/csv_renderer.rb) , making it impossible to write tests for it (we needed it recently and wasn't able to) and it's also not a good practice to put so much logic in an initializer.

### How

We need to extract this logic into an operation and write tests for all the possible cases:

- project with no notes, neither attachments or tasks (don't mistake tasks with stories)
- project with notes but no attachments or tasks
- project with no notes or tasks, but with attachments
- project with no notes or attachments, but with tasks
- project with notes and attachments, but no tasks
- project with notes and tasks, but no attachments
- project with no notes, but with attachments and tasks
- project with notes, attachments and tasks
- project with no story

**Comment by kostadriano** [comment]
[#528](https://github.com/Codeminer42/cm42-central/pull/528) closes this issue, thanks @wenderjean.
