### ISSUE TITLE
Uploading should automatically save when done.

### ISSUE THREAD

**Issue by akitaonrails** [Codeminer42/cm42-central#55]
Currently you need to manually click "Save" on the Story View after the upload is done. I think we can trigger the save function just after the uploading instead. Many people are probably uploading stuff and not saving and they think the upload is failing.

@rscardinho @daniloisr @adbatista

**Comment by adbatista** [comment]
I'll take it

**Comment by CaiqueMitsuoka** [comment]
Done.
