### ISSUE TITLE
Mimic the new Pivotal Tracker look and feel

### ISSUE THREAD

**Issue by akitaonrails** [Codeminer42/cm42-central#62]
The old Fulcrum project tried to mimic the old Pivotal Tracker looks.

We should be able to upgrade the UI (CSS, etc) to make it closer to the new Tracker looks.

This is a complete UI overhaul, probably lengthy, so move with care and do "horizontal changes" first. For example, change the color palette first and merge. Then change typography and merge. Then change specific element spacing and merge. Instead of doing everything at once, that way we can move one step at a time.

**Comment by FidelisClayton** [comment]
Can you move the card to progress?

**Comment by PedroFelipe** [comment]
@FidelisClayton's first proposal has a PR and it is about to be merged: #85

**Comment by PedroFelipe** [comment]
# January 11-18

## Authentication
I'll be working to redesign all authentication views (sign in, sign up, password recover and resend confirmation instructions), redesigning the UI and working to enhance the user experience making all these pages more presentable and less Bootstrap-like.

Current state:
![screen shot 2017-01-11 at 11 08 45 am](https://cloud.githubusercontent.com/assets/463661/21851567/5f93697c-d7ee-11e6-8bf5-bfc0f52dcc38.png)
![screen shot 2017-01-11 at 11 08 51 am](https://cloud.githubusercontent.com/assets/463661/21851565/5f8bac6e-d7ee-11e6-904a-955e229d5cbf.png)
![screen shot 2017-01-11 at 11 08 54 am](https://cloud.githubusercontent.com/assets/463661/21851566/5f8bcd48-d7ee-11e6-8700-37117dca311a.png)

**Comment by FidelisClayton** [comment]
# January 11-18

## Teams
Here the main idea is to replace the `select input` and use cards to display the teams and some information about them.

#### Current state:
![teams](http://i.imgur.com/JuoIlYq.png)

## Projects
On projects page, we should improve the current project timeline style and display the projects using cards.

#### Current state:
![projects](http://i.imgur.com/IUMJfLa.png)

**Comment by marcosjr182** [comment]
# January 11-18

## Redesign of Importations, Import and Reports pages
I will be using a card-like container on these pages to center their content and working to improve their UI in order to provide a better user experience.

![import](https://cloud.githubusercontent.com/assets/5242693/21853942/bedb94b4-d7f7-11e6-8294-63b686c4ec5b.png)

![integrations](https://cloud.githubusercontent.com/assets/5242693/21853968/d1d9fe48-d7f7-11e6-92b2-ed83de88b861.png)

On reports page there will be tabs to separate the 'Burn Up Chart' and the other reports. The remaining reports will be placed on a single tab.

![reports](https://cloud.githubusercontent.com/assets/5242693/21853986/df59a1ea-d7f7-11e6-9c47-6a78e7853212.png)

**Comment by akitaonrails** [comment]
@PedroFelipe @marcosjr182 @FidelisClayton 

I agree with the tasks but be careful. They are basically bare bone Bootstrap. 

I believe that tweaking Bootstrap will take care of making the elements/components prettier.

I am not against removing Bootstrap. But be careful so this don't take forever to make.

What's left would be using proper panels/cards to take care of horizontal spacing and placements.

The Reports page should be last. The idea is to make the information quickly accessible and I am not sure if having tabs will only obscure the information.

The main project page (story view) is the top priority as it's the place that most people use more often.

So I'd say that all those screens are "good to improve" but shouldn't take too long. And more time and priority should be given to the main project page.
