### ISSUE TITLE
Remake the Login sequence

### ISSUE THREAD

**Issue by akitaonrails** [Codeminer42/cm42-central#66]
Currently I have a convoluted method of signing up with the mandatory "team" field. We can either type in the team slug name there or use a URL with the team name that will set a session.

It's convoluted. The correct way would be to remove this field again from the sign in form and remove this URL non-sense.

The correct way is to have a normal sign in page. Then if the current_team is nil it forwards to a /users/xyz/teams that lists the user's teams so the user can POST the team he wants, which will set the current_team and that's it.

"Forgot password" should follow the same logic.

**Comment by talyssonoc** [comment]
@eddiecode what do you think about getting this one?
