### ISSUE TITLE
Add a "History" view for a Story

### ISSUE THREAD

**Issue by akitaonrails** [Codeminer42/cm42-central#72]
Every Story already has every change recorded in the polymorphic Activity model. We need to show it in a new Column View. Each Activity row can be a foldable item in this new Column.

The Column must be of the format "History of "[title of the story]"".

This is the look and feel from Pivotal Tracker:

![escola_digital_-_demo_-_pivotal_tracker](https://cloud.githubusercontent.com/assets/2840/20494930/2d75ffd2-b006-11e6-9121-112c62cfce4c.png)

In Tracker each Story History gets its own separated Column, but to make it simpler, we can reuse the same column and every time we click on the "History" icon in the Story View, we reset the Column.

We probably need a (backbone based) Activity View and a new ActivityColumn View or something similar. Possibly an ActivityCollection (backbone based) model and another Activity Model as well. Most of the work will be on the Javascript side and a simple controller that can receive the Story id and send a collection of Activities.

**Comment by adbatista** [comment]
@CaiqueMitsuoka I thinks this is something that you can solve, could you work on this?

**Comment by CaiqueMitsuoka** [comment]
@adbatista @akitaonrails I'll do.
