### ISSUE TITLE
Connect users with mattermost, by project integration

### ISSUE THREAD

**Issue by andrerpbts** [Codeminer42/cm42-central#75]
We should be able to add a dropdown that fetches the usernames from mattermost in the new user/edit user forms. And a Rake task to compare the existing usernames/emails with mattermost so we can fix the usernames and use them in the future to send direct messages from Central-Bot for example

**Comment by amalrik** [comment]
Hi @andrerpbts 
How the dropdown is supposed to behave in case a team has 200 users for example?
What do you think about consult mattermost API with ajax and show a list of users matching the user name 

Heres the endpoint that could be used to search for users:
`https://your-mattermost-url.com/api/v3/users/search`

Please let me know you think.

**Comment by andrerpbts** [comment]
I agree.

This task needs to be evaluated yet.

**Comment by wenderjean** [comment]
@amalrik @andrerpbts Do you think to put a new field like a typeahead or use/filter by `username` field?
This task can already be done or does it need more considerations?

**Comment by andrerpbts** [comment]
Need more considerations yet, Wender. 

In fact, I suppose this task might be totally rethinked as well, since I just splited this from another issue and this feature doesn't make much sense now. Each project has it own integrations with the apps, MM for now (but could have integration with another apps in the future), and a user can be in more than one project. So, imagine the scenario when a user is in 2 projects, and each project is integrated with a distinct MM server from another, and the username changes in both of them. With this task implemented in this way, it will fail to accomplish those requirements.

I think we need a screen when user can see its membership of a project and configure things like it. It would be a `User's project settings`, and there, all integrations and user preferences for that project would be editable for the user.

Last, we need to check with @akitaonrails, if he has some idea in mind to use integrations in a user context, otherwise this implementation would be a lost of time now.

**Comment by andrerpbts** [comment]
Actually this issue don't sound making sense. Closing this issue for now.
