### ISSUE TITLE
Convert ExpandedStoryLabels to be a functional component

### ISSUE THREAD

**Issue by talyssonoc** [Codeminer42/cm42-central#862]
Convert the component at file https://github.com/Codeminer42/cm42-central/blob/master/app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryLabels.jsx to be a functional component instead of a class

**Comment by joaoGabriel55** [comment]
I can work on that!

**Comment by talyssonoc** [comment]
Go for it!
